apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yml

# helmCharts:
# - name: kube-prometheus-stack
#   repo: https://prometheus-community.github.io/helm-charts
#   version: 70.4.1
#   valuesFile: values.yml

# helm -n monitoring install -f values.yaml --generate-name prometheus-community/kube-prometheus-stack