apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.10-192.168.1.19
    - name: zmh-netsrv
      protocol: layer2
      addresses:
      - 192.168.1.20-192.168.1.39
