apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.223.1.1-10.223.1.100
    - name: zmh-netsrv
      protocol: layer2
      addresses:
      - 10.223.10.1-10.223.10.100
    - name: zmh-gameservices
      protocol: layer2
      addresses:
      - 10.223.20.1-10.223.20.100
