apiVersion: v1
kind: Namespace
metadata:
  name: zmh-gamesrv-valheim
  labels:
    name: zmh-gamesrv-valheim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zmh-gameservices-valheim
  namespace: zmh-gamesrv-valheim
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/valheim
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - zmh-homeservices-003

---
apiVersion: v1
kind: Service
metadata:
  name: zmh-gameservices-valheim
  namespace: zmh-gamesrv-valheim
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: interface
    port: 2456
    protocol: TCP
    targetPort: interface
  selector:
    app: wispvalheim
  loadBalancerIP: 192.168.1.45

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wispvalheim
  namespace: zmh-gamesrv-valheim
spec:
  selector:
    matchLabels:
      app: wispvalheim # has to match .spec.template.metadata.labels
  serviceName: "wispvalheim"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: wispvalheim # has to match .spec.selector.matchLabels
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      containers:
      - name: wispvalheim
        image: lloesche/valheim-server
        imagePullPolicy: Always
        env:
        - name: SERVER_NAME
          value: "WISPYValheim"
        - name: SERVER_PORT
          value: "2456"
        - name: WORLD_NAME
          value: NordBelka
        - name: SERVER_PASS
          value: "whisper"
        - name: SERVER_PUBLIC
          value: "true"
        - name: UPDATE_CRON
          value: "0 */4 * * *"
        - name: UPDATE_IF_IDLE
          value: "true"
        - name: RESTART_CRON
          value: "0 5 * * *"
        - name: RESTART_IF_IDLE
          value: "true"
        - name: TZ
          value: "America/Chicago"
        - name: BACKUPS
          value: "true"
        - name: BACKUPS_CRON
          value: "0 */6 * * *"
        - name: BACKUPS_DIRECTORY
          value: "/config/backups"
        - name: BACKUPS_MAX_AGE
          value: "3"
        - name: BACKUPS_MAX_COUNT
          value: "0"
        - name: BACKUPS_IF_IDLE
          value: "false"
        - name: BACKUPS_ZIP
          value: "true"
        - name: STEAMCMD_ARGS
          value: "validate"
        - name: VALHEIM_PLUS
          value: "true"
        ports:
        - name: interface
          containerPort: 2456
          protocol: TCP
        volumeMounts:
        - name: zmh-gameservices-valheim
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: zmh-gameservices-valheim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 20Gi
