apiVersion: v1
kind: Service
metadata:
  name: paper-minecraft
  namespace: games
  annotations:
    metallb.io/address-pool: games
  labels:
    app: minecraft
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: interface
    port: 25565
    protocol: TCP
    targetPort: interface
  - name: rcon
    port: 25570
    protocol: TCP
    targetPort: rcon
  selector:
    app: minecraft