apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "paper-minecraft"
  namespace: "games"
spec:
  selector:
    matchLabels:
      app: minecraft # has to match .spec.template.metadata.labels
      type: latest-build
  serviceName: "paper-minecraft"
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft # has to match .spec.selector.matchLabels
        type: latest-build
    spec:
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "gameserver"
        effect: "NoSchedule"
      containers:
      - name: paper-minecraft
        image: itzg/minecraft-server:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "10000m"
            memory: "8Gi"
        env:
        - name: TYPE
          value: "PAPER"
        - name: VERSION
          value: "LATEST"
        - name: SERVER_PORT
          value: "25565"
        - name: OVERRIDE_SERVER_PROPERTIES
          value: "false"
        - name: OPS
          value: "chillpickles"
        - name: EULA
          value: "true"
        - name: MOTD
          value: "Welcome to a Chillcraft Experience"
        - name: DIFFICULTY
          value: "normal"
        - name: MAX_TICK_TIME
          value: "60000"
        - name: SPAWN_PROTECTION
          value: "10"
        - name: VIEW_DISTANCE
          value: "30"
        - name: OVERRIDE_ICON
          value: "false"
        - name: ENABLE_RCON
          value: "true"
        - name: RCON_PORT
          value: "25575"
        - name: RCON_PASSWORD
          value: "PurplePorpoise"
        - name: MAX_PLAYER
          value: "20"
        - name: ALLOW_NETHER
          value: "true"
        - name: LEVEL
          value: "average_world"
        - name: ALLOW_FLIGHT
          value: "true"
        - name: SERVER_NAME
          value: "Chillcraft"
        - name: INIT_MEMORY
          value: "2G"
        - name: MAX_MEMORY
          value: "8G"
        ports:
        - name: interface
          containerPort: 25565
          protocol: TCP
        - name: rcon
          containerPort: 25570
          protocol: TCP
        volumeMounts:
        - name: papermc-save
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: papermc-save
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 30Gi
