apiVersion: v1
kind: Service
metadata:
  name: wireguard-server
  namespace: wireguard
  annotations:
    metallb.universe.tf/IPaddress-pool: wireguard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: udp-wireguard
    protocol: UDP
    port: 51820
    targetPort: 51820
  selector:
    app: wireguard
