apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- metallb-native.yml
- ipaddresspool.yml
- l2advertisement.yml

patches:
  - path: taint-compat.yml
    target:
      kind: DaemonSet
      name: speaker