apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9001
    targetPort: 9001
    name: ui
  - port: 9000
    targetPort: 9000
    name: cli
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio
        imagePullPolicy: IfNotPresent
        command: ["minio"]
        args: ["server", "--console-address=:9001"]
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: MINIO_DOMAIN
          value: "minio.lavender.chillpickles.digital"
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: username
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: password
        - name: MINIO_VOLUMES
          value: "/data"
        ports:
        - containerPort: 9001
          name: ui
        - containerPort: 9000
          name: cli
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /root/.minio
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ui
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: minio.lavender.chillpickles.digital
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              name: ui
  - host: s3.lavender.chillpickles.digital
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              name: cli