apiVersion: apps/v1
kind: Deployment
metadata:
  name: steamcmd
  labels:
    app: steamcmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steamcmd
  template:
    metadata:
      labels:
        app: steamcmd
    spec:
      containers:
      - name: steamcmd
        image: cm2network/steamcmd:latest
        ports:
        - containerPort: 80