apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: omv
  namespace: default
  labels:
    kubernetes.io/service-name: omv
addressType: IPv4
ports:
  - port: 80
endpoints:
  - addresses:
      - "10.79.2.108"
    conditions:
      ready: true
---
apiVersion: v1
kind: Service
metadata:
  name: omv
  namespace: default
spec:
  clusterIP: "None"
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omv
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: omv.lavender.chillpickles.digital
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: omv
            port:
              name: http