apiVersion: v1
kind: Namespace
metadata:
  name: zmh-gamesrv-ark
  labels:
    name: zmh-gamesrv-ark

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zmh-gameservices-arksurvival
  namespace: zmh-gamesrv-ark
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/arksurvival
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - zmh-gameservices-test1

---
apiVersion: v1
kind: Service
metadata:
  name: zmh-gameservices-arksurvival
  namespace: zmh-gamesrv-ark
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: game-client
    port: 7777
    protocol: TCP
    targetPort: game-client
  - name: udp-socket
    port: 7778
    protocol: TCP
    targetPort: udp-socket
  - name: rcon-port
    port: 27020
    protocol: TCP
    targetPort: rcon-port
  - name: server-list
    port: 27015
    protocol: TCP
    targetPort: server-list
  selector:
    app: ark-survival
  loadBalancerIP: 192.168.1.28

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zmh-gameservices-arksurvival
  namespace: zmh-gamesrv-ark
spec:
  selector:
    matchLabels:
      app: ark-survival # has to match .spec.template.metadata.labels
  serviceName: "ark-survival"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: ark-survival # has to match .spec.selector.matchLabels
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      containers:
      - name: ark-survival
        image: Hermsi1337/docker-ark-server:latest
        imagePullPolicy: Always
        env:
        - name: SESSION_NAME
          value: "The Family's Ark Server by github.com/chillpickles"
        - name: SERVER_MAP
          value: "TheIsland"
        - name: SERVER_PASSWORD
          value: "tooshort"
        - name: ADMIN_PASSWORD
          value: "CardIng123"
        - name: MAX_PLAYERS
          value: "20"
        - name: UPDATE_ON_START
          value: "true"
        - name: PRE_UPDATE_BACKUP
          value: "true"
        - name: WARN_ON_STOP
          value: "true"
        - name: ENABLE_CROSSPLAY
          value: "true"
        - name: DISABLE_BATTLEYE
          value: "true"
        - name: ARK_SERVER_VOLUME
          value: /app
        - name: GAME_CLIENT_PORT
          value: "7777"
        - name: UDP_SOCKET_PORT
          value: "7778"
        - name: RCON_PORT
          value: "27020"
        - name: SERVER_LIST_PORT
          value: "27015"
        ports:
        - name: game_client_port
          containerPort: 7777
          protocol: TCP
        - name: udp_socket_port
          containerPort: 7778
          protocol: TCP
        - name: RCON_PORT
          containerPort: 27020
          protocol: TCP
        - name: server_list_port
          containerPort: 27015
          protocol: TCP
        volumeMounts:
        - name: zmh-gameservices-arksurvival
          mountPath: /app
  volumeClaimTemplates:
  - metadata:
      name: zmh-gameservices-arksurvival
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 40Gi