apiVersion: v1
kind: Namespace
metadata:
  name: zmh-gamesrv
  labels:
    name: zmh-gamesrv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zmh-gameservices-foundryvtt
  namespace: zmh-gamesrv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/foundryvtt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - zmh-homeservices-003

---
apiVersion: v1
kind: Service
metadata:
  name: zmh-gameservices-foundryvtt
  namespace: zmh-gamesrv
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: interface
    port: 30000
    protocol: TCP
    targetPort: interface
  selector:
    app: foundryvtt
  loadBalancerIP: 192.168.1.30

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foundryvtt
  namespace: zmh-gamesrv
spec:
  selector:
    matchLabels:
      app: foundryvtt # has to match .spec.template.metadata.labels
  serviceName: "foundryvtt"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: foundryvtt # has to match .spec.selector.matchLabels
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      containers:
      - name: foundryvtt
        image: felddy/foundryvtt:release
        imagePullPolicy: Always
        env:
        - name: port
          value: "3000"
        - name: FOUNDRY_USERNAME
          value: chillary
        - name: FOUNDRY_PASSWORD
          value: ""
        ports:
        - name: interface
          containerPort: 30000
          protocol: TCP
        volumeMounts:
        - name: zmh-gameservices-foundryvtt
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: zmh-gameservices-foundryvtt
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 100Gi
