apiVersion: v1
kind: Namespace
metadata:
  name: zmh-gamesrv
  labels:
    name: zmh-gamesrv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zmh-gameservices-foundryvtt
  namespace: zmh-gamesrv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/foundryvtt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - zmh-homeservices-003
