apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp
  namespace: homeservices-unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-controller"
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - port: 3478
    name: "3478"
    protocol: UDP
  - port: 10001
    name: "10001"
    protocol: UDP
  loadBalancerIP: 192.168.1.25

---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-tcp
  namespace: homeservices-unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-controller"
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - port: 8080
    name: "8080"
  - port: 8443
    name: "8443"
  - port: 8843
    name: "8843"
  - port: 8880
    name: "8880"
  - port: 6789
    name: "6789"
  loadBalancerIP: 192.168.1.25
