## Helm Configuration for zmh-blue cluster last updated 20250312

grafana:
  service:
    type: "LoadBalancer"
  ingress:
    enabled: "true"
    ingressClassName: "nginx"
    hosts: ["grafana.blue.chillpickles.digital"]
prometheus:
  prometheusSpec:
    retention: 180d