apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-nginx-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: zmh-rock5-001
  - matchLabels:
      kubernetes.io/hostname: zmh-blue-001
  - matchLabels:
      kubernetes.io/hostname: zmh-blue-002
  - matchLabels:
      kubernetes.io/hostname: zmh-blue-003