apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-nginx-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
  nodeSelectors:
  - matchLabels:
      kubernetes.io/os: linux