apiVersion: v1
kind: Endpoints
metadata:
  name: synology
  namespace: default
subsets:
- addresses:
  - ip: 10.79.1.79
  ports:
  - port: 5000
    protocol: TCP
    name: http
  - port: 5001
    protocol: TCP
    name: https
---
apiVersion: v1
kind: Service
metadata:
  name: synology
  namespace: default
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
  - name: https
    port: 5001
    protocol: TCP
  selector: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-synology
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: "synology.local.chillpickles.digital"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: synology
            port:
              number: 5000