kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-gamesrv
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  recurringJobSelector: '[{"name":"gamesrv", "isGroup":true}]'
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-active
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  recurringJobSelector: '[{"name":"active", "isGroup":true}]'
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-stable
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  recurringJobSelector: '[{"name":"stable", "isGroup":true}]'
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-static
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  recurringJobSelector: '[{"name":"static", "isGroup":true}]'